### ISSUE TITLE
关于1.5.4.4版本的POI发送数据经常错误,且通知栏不能显示掉落

### ISSUE THREAD

**Issue by ghost** [tsanie/ElectronicObserver#11]
提交 poi-statistics 时发生错误：与“System.Array.Copy(System.Array, int, System.Array, int, int)”最匹配的重载方法具有一些无效参数 : 与“System.Array.Copy(System.Array, int, System.Array, int, int)”最匹配的重载方法具有一些无效参数

**Comment by tsanie** [comment]
关于这个问题请更新到 3cc128ba6646f6144cfdc39d77023edc667b2c47 的版本。
二进制可以在这里下载 https://ci.appveyor.com/project/tsanie/electronicobserver-pgsm1/build/artifacts
下载其中的DBSender.dll，Battles.dll覆盖。
